services:
  openmower-map-editor:
    build:
       context: .
       dockerfile: Dockerfile
       platforms:
         - linux/amd64
         - linux/arm64
    image: ghcr.io/revlaw/openmowermapeditor:dev
    container_name: openmower-map-editor
    ports:
      - "5080:80"
    volumes:
      - type: bind
        source: ./params
        target: /data/params
        read_only: true
      - type: bind
        source: ./ros
        target: /data/ros
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    environment:
      OPENMOWER_CONTAINER_NAME: open_mower_ros
